server_port: 8765
entity_id: "https://fedservice.jisc.ac.uk:8765"
#authority_hints:
#  - "https://fedservice.jisc.ac.uk"
signing_key_file: "jisc/ecdsa_private_key_pkcs8.pem"
organization_name: "Jisc Trust Anchor"
data_location: "jisc"
human_readable_storage: true
metadata_policy_file: "jisc/metadata-policy.json"
endpoints:
  fetch:
    path: "/fetch"
  list:
    path: "/list"
  resolve:
    path: "/resolve"
  trust_mark:
    path: "/trustmark"
  trust_mark_status:
    path: "/trustmark/status"
  trust_mark_list:
    path: "/trustmark/list"
  enroll:
    path: "/enroll"
    checker:
      type: none
      #type: multiple_or
      # config:
      #   - type: trust_mark
      #     config:
      #       trust_mark_id: https://tm.example.org
      #       trust_anchors:
      #         - entity_id: https://ta.example.org
      #   - type: trust_mark
      #     config:
      #       trust_mark_id: https://tm.example.com
      #       trust_anchors:
      #         - entity_id: https://example.com
      #         - entity_id: https://foo.bar.com
trust_mark_specs:
  - trust_mark_id: "https://www.ukfederation.org.uk/member"
    lifetime: 7200
    logo_uri: "https://www.ukfederation.org.uk/images/orange-topv3.jpg"
    checker:
      type: trust_path
      config:
        trust_anchors:
          - entity_id: "https://fedservice.jisc.ac.uk:8765"
trust_marks:
  - trust_mark_id: "https://www.ukfederation.org.uk/member"
    trust_mark_issuer: "https://fedservice.jisc.ac.uk:8765"
